version: '3'

services:
  playit:
    network_mode: host
    container_name: playit
    image: ghcr.io/playit-cloud/playit-agent:0.15
    restart: unless-stopped
    network_mode: host
    environment:
    - SECRET_KEY=${PLAYIT_SECRET_KEY}
