version: '3.8'

services:
  minecraft:
    image: marctv/minecraft-papermc-server:1.21.1-57
    container_name: minecraft_service
    environment:
      - EULA=TRUE
      - TYPE=paper
      - MEMORY=4G
    volumes:
      - ./volume:/data
    restart: unless-stopped
    network_mode: host
